common: &common
  precision: "16.16"
  replicas: 1
  device_iterations: 128
  half_partial: true
  norm_type: batch
  eight_bit_io: true
  normalization_location: ipu


resnet50:
  <<: *common
  model: resnet50
  micro_batch_size: 90


efficientnet-b0:
  <<: *common
  model: efficientnet-b0
  micro_batch_size: 49


efficientnet-b4:
  <<: *common
  model: efficientnet-b4
  micro_batch_size: 12


efficientnet-g16-gn: &efficientnet-g16-gn
  <<: *common
  efficientnet_group_dim: 16
  efficientnet_expand_ratio: 4
  norm_type: group
  norm_eps: 0.001
  norm_num_groups: 4
  enable_fast_groupnorm: true
  random_weights: true


efficientnet-b0-g16-gn:
  <<: *efficientnet-g16-gn
  model: efficientnet-b0
  micro_batch_size: 106


efficientnet-b4-g16-gn:
  <<: *efficientnet-g16-gn
  model: efficientnet-b4
  micro_batch_size: 26


mobilenet-v3-small:
  <<: *common
  model: mobilenet-v3-small
  micro_batch_size: 224
  device_iterations: 64


mobilenet-v3-large:
  <<: *common
  model: mobilenet-v3-large
  micro_batch_size: 64
